version: '3'

services:

  app: 
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app

  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=mercafacilDb
    - MYSQL_PASSWORD=admin
    # - MYSQL_ROOT_HOST=localhost
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password